name: Label to Title

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  whatever-you-call-the-job:
    runs-on: ubuntu-latest
    steps:
    - uses: pyiron/actions/label-to-title@label-to-title
